language: ruby
rvm:
  - 2.4.1
cache:
  - bundler

script: bundle exec rake test

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: _site

env:
  global:
    # Speed up installation of html-proofer
    - NOKOGIRI_USE_SYSTEM_LIBRARIES: true

sudo: false

addons:
  apt:
    packages:
      - aspell
      - aspell-en