dist: bionic
language: ruby
rvm:
  - 2.5.5
cache:
  - bundler

script: bundle exec rake test

deploy:
  provider: pages
  token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: _site

env:
  global:
    # Speed up installation of html-proofer
    - NOKOGIRI_USE_SYSTEM_LIBRARIES: true

addons:
  apt:
    packages:
      - aspell
      - aspell-en