18+:
 text: "You usually need to be at least 18"
 icon: age18
16+:
 text: "You usually need to be at least 16"
 icon: age16
bmi:
 text: "You may need to have a certain BMI (body mass index) to get this"
 icon: bmi
tanner2:
 text: "Under 18s must be at [Tanner Stage 2](\"/resources/tanner-stage\") or later"
 icon: puberty
parents:
 text: "Under 18s can usually only get this with the support of their parents or guardians"
 icon: family
time:
 icon: time
consent:
 text: "You must have capacity to consent for this treatment"
 icon: consent
hrt:
 icon: medication
not-standalone:
 text: "This is usually only commissioned as part of other treatments"
 icon: linked
