name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.5
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5
    - name: Build and test with Rake
      run: |
        gem install bundler
        sudo apt-get install libimlib2-dev aspell aspell-en
        bundle install --jobs 4 --retry 3
        bundle exec rake
